strings:
  ru:
    main_menu: "Главное меню"
    menu:
      language: "Выберите язык"
      start_chat: "Начать чат"
      short_mode: "Краткое объяснение"
      step_by_step_mode: "Пошаговое объяснение"
      billing: "Тарифный план"
      feedback: "Обратная связь"
    ask_query: "Введите вашу задачу текстом или отправьте изображение"
  en:
    main_menu: "Main menu"
    menu:
      language: "Choose language"
      start_chat: "Start chat"
      short_mode: "Short explanation"
      step_by_step_mode: "Step-by-step explanation"
      billing: "Billing"
      feedback: "Feedback"
    ask_query: "Enter your problem in text or send an image"
    response:
      step_by_step: "Step-by-step explanation avaliable at the link: {link}"
    
prompts:
  - id: 1
    name: "Short exaplantion"
    base: |
      Please provide a short explanation of the solution for the problem.
      Write final answer to the problem as a json block with a key "answer" and a value like "x = 5".
      If the problem is not correct or it is not mathematical problem, inform the user that one needs to state correct mathematical problem.
    text_intput: |
      {base} The problem: {user_message}
    image_input: |
      {base} The problem is statued in the image.
    image_text_input: |
      {image_input} The comment to the image is: {user_message}
  - id: 2
    name: "Step-by-step explanation."
    base: |
      Please provide a detailed step-by-step explanation of the solution for the problem. Be pedagogical and patient.
      Use latex language to write your formulas. Format your response as a html page with latex support.
      If the problem is not correct or it is not mathematical problem, inform the user that one needs to state correct mathematical problem.
    text_intput: |
      {base} The problem: {user_message}
    image_input: |
      {base} The problem is statued in the image.
    image_text_input: |
      {image_input} The comment to the image is: {user_message}
